# Generated by Django 2.1.2 on 2019-01-05 08:37

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('type', models.CharField(editable=False, max_length=30)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='AssetSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_video_width', models.SmallIntegerField(default=480)),
                ('default_video_height', models.SmallIntegerField(default=360)),
                ('default_video_autoplay', models.BooleanField(default=False)),
                ('default_video_controls', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Asset Settings',
            },
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset')),
                ('asset', models.FileField(upload_to='assets/file/')),
            ],
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset')),
                ('asset', sorl.thumbnail.fields.ImageField(upload_to='assets/image/')),
            ],
            bases=('assets.asset',),
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='assets.Asset')),
                ('asset', models.FileField(upload_to='assets/video/')),
                ('video_width', models.SmallIntegerField(default=None, null=True)),
                ('video_height', models.SmallIntegerField(default=None, null=True)),
                ('autoplay', models.BooleanField(default=False)),
                ('controls', models.BooleanField(default=True)),
                ('loop', models.BooleanField(default=False)),
            ],
            bases=('assets.asset',),
        ),
    ]
