# Generated by Django 2.1.7 on 2019-02-19 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='tag',
            field=models.CharField(default=None, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='slug',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='title',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
