# Generated by Django 2.1.2 on 2018-12-02 00:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('type', models.CharField(editable=False, max_length=30)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('link_name', models.CharField(max_length=40, unique=True)),
                ('keywords', models.CharField(blank=True, default=None, max_length=120, null=True)),
                ('passthrough_page', models.BooleanField(default=False)),
                ('passthrough_link', models.CharField(blank=True, default=None, max_length=40, null=True)),
                ('custom_css', models.FileField(blank=True, default=None, null=True, upload_to='style/')),
                ('custom_javascript', models.FileField(blank=True, default=None, null=True, upload_to='scripts/')),
                ('content', models.TextField(blank=True, default=None, null=True)),
                ('the_order', models.PositiveIntegerField(db_index=True, default=0, editable=False)),
            ],
            options={
                'ordering': ['the_order'],
            },
        ),
        migrations.CreateModel(
            name='SiteAdminSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('err_404_title', models.CharField(default='Page not Found (404)', max_length=60)),
                ('err_404_content', models.TextField(blank=True, default=None, null=True)),
                ('err_500_title', models.CharField(default='Server Error (500)', max_length=60)),
                ('err_500_content', models.TextField(blank=True, default=None, null=True)),
                ('default_video_width', models.SmallIntegerField(default=480)),
                ('default_video_height', models.SmallIntegerField(default=360)),
                ('default_video_autoplay', models.BooleanField(default=False)),
                ('default_video_controls', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Site Admin Settings',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, unique=True)),
                ('meta_description', models.CharField(max_length=120, null=True)),
                ('meta_author', models.CharField(max_length=100, null=True)),
                ('meta_keywords', models.CharField(max_length=120, null=True)),
                ('number_recent_posts', models.PositiveSmallIntegerField(blank=True, default=3, null=True, validators=[django.core.validators.MaxValueValidator(3)], verbose_name='Number of recent posts to show')),
                ('google_analytics_key', models.CharField(blank=True, max_length=120, null=True)),
                ('github_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='FileAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='douglasdaly.Asset')),
                ('asset', models.FileField(upload_to='assets/file/')),
            ],
            bases=('douglasdaly.asset',),
        ),
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='douglasdaly.Asset')),
                ('asset', sorl.thumbnail.fields.ImageField(upload_to='assets/image/')),
            ],
            bases=('douglasdaly.asset',),
        ),
        migrations.CreateModel(
            name='VideoAsset',
            fields=[
                ('asset_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='douglasdaly.Asset')),
                ('asset', models.FileField(upload_to='assets/video/')),
                ('video_width', models.SmallIntegerField(default=None, null=True)),
                ('video_height', models.SmallIntegerField(default=None, null=True)),
                ('autoplay', models.BooleanField(default=False)),
                ('controls', models.BooleanField(default=True)),
                ('loop', models.BooleanField(default=False)),
            ],
            bases=('douglasdaly.asset',),
        ),
    ]
