# Generated by Django 2.1.2 on 2019-01-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('douglasdaly', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileasset',
            name='asset_ptr',
        ),
        migrations.RemoveField(
            model_name='imageasset',
            name='asset_ptr',
        ),
        migrations.RemoveField(
            model_name='videoasset',
            name='asset_ptr',
        ),
        migrations.RemoveField(
            model_name='siteadminsettings',
            name='default_video_autoplay',
        ),
        migrations.RemoveField(
            model_name='siteadminsettings',
            name='default_video_controls',
        ),
        migrations.RemoveField(
            model_name='siteadminsettings',
            name='default_video_height',
        ),
        migrations.RemoveField(
            model_name='siteadminsettings',
            name='default_video_width',
        ),
        migrations.AddField(
            model_name='page',
            name='published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteadminsettings',
            name='err_404_sentry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteadminsettings',
            name='err_500_sentry',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='siteadminsettings',
            name='inactive_page_content',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='siteadminsettings',
            name='inactive_page_title',
            field=models.CharField(default='Undergoing Maintenance', max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='siteadminsettings',
            name='site_is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='siteadminsettings',
            name='err_404_title',
            field=models.CharField(default='Page not Found (404)', max_length=80),
        ),
        migrations.AlterField(
            model_name='siteadminsettings',
            name='err_500_title',
            field=models.CharField(default='Server Error (500)', max_length=80),
        ),
        migrations.DeleteModel(
            name='Asset',
        ),
        migrations.DeleteModel(
            name='FileAsset',
        ),
        migrations.DeleteModel(
            name='ImageAsset',
        ),
        migrations.DeleteModel(
            name='VideoAsset',
        ),
    ]
