# Generated by Django 2.1.2 on 2018-12-02 00:57

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=100)),
                ('posts_per_page', models.PositiveIntegerField(default=10)),
                ('code_style_sheet', models.CharField(choices=[('code_default', 'Default'), ('code_monokai', 'Monokai')], default='code_default', max_length=40)),
            ],
            options={
                'verbose_name_plural': 'Blog Settings',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('slug', models.SlugField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CustomCSS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(upload_to='blog/posts/custom_css/')),
            ],
            options={
                'verbose_name_plural': 'Custom CSS Files',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CustomJS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('file', models.FileField(upload_to='blog/posts/custom_js/')),
            ],
            options={
                'verbose_name_plural': 'Custom JS Files',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon_image', sorl.thumbnail.fields.ImageField(blank=True, default=None, null=True, upload_to='blog/posts/icons/')),
                ('description', models.TextField(default='', null=True)),
                ('body', models.TextField()),
                ('custom_javascript', models.FileField(blank=True, default=None, null=True, upload_to='blog/posts/scripts/')),
                ('posted', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('published', models.BooleanField(default=False)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category')),
                ('css_includes', models.ManyToManyField(blank=True, to='blog.CustomCSS')),
                ('javascript_includes', models.ManyToManyField(blank=True, to='blog.CustomJS')),
            ],
            options={
                'ordering': ('-posted',),
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField()),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
