# Generated by Django 2.1.2 on 2019-01-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsettings',
            name='feed_most_recent_number',
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
