# Generated by Django 2.1.5 on 2019-01-31 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190105_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='_category',
            field=models.CharField(default='A', max_length=1),
            preserve_default=False,
        ),
    ]
