# Generated by Django 2.1.2 on 2019-01-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogsettings_feed_most_recent_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogsettings',
            old_name='feed_most_recent_number',
            new_name='latest_feed_most_recent',
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='site_link',
            field=models.CharField(default='blog', max_length=40),
        ),
    ]
