# Generated by Django 2.1.2 on 2019-01-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190104_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
