# Generated by Django 2.1.7 on 2019-02-19 02:37

import blog.fields
import colorful.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_tag__category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=140)),
                ('first_name', models.CharField(max_length=60, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, default=None, max_length=60, null=True, verbose_name='Last Name')),
                ('display_name', models.CharField(blank=True, default=None, max_length=80, null=True, verbose_name='Pen Name (display)')),
                ('author_image', models.ImageField(blank=True, default=None, null=True, upload_to='blog/authors/images/', verbose_name="Author's Image")),
                ('author_bio', models.TextField(blank=True, default=None, null=True, verbose_name='Author Biography')),
                ('author_website', models.URLField(blank=True, default=None, null=True, verbose_name="Author's Website")),
                ('contact_email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Contact Email')),
                ('public_contact_email', models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Display Email (public)')),
                ('display_public_email', models.BooleanField(default=False, verbose_name='Display public email?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('show_posts', models.BooleanField(default=True, verbose_name='Show Posts')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('display_name', 'last_name', 'first_name'),
            },
        ),
        migrations.CreateModel(
            name='ColorTheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100)),
                ('colors', blog.fields.ListField(token=',')),
            ],
            options={
                'verbose_name': 'Color Theme',
            },
        ),
        migrations.AlterModelOptions(
            name='customcss',
            options={'ordering': ('tag', 'name'), 'verbose_name': 'Custom CSS', 'verbose_name_plural': 'Custom CSS Files'},
        ),
        migrations.AlterModelOptions(
            name='customjs',
            options={'ordering': ('tag', 'name'), 'verbose_name': 'Custom JS', 'verbose_name_plural': 'Custom JS Files'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-display_date',)},
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='show_authors',
            field=models.BooleanField(default=False, verbose_name='Show Authors'),
        ),
        migrations.AddField(
            model_name='category',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='font_color',
            field=colorful.fields.RGBColorField(default='#000000'),
        ),
        migrations.AddField(
            model_name='category',
            name='icon_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blog/categories/icons/'),
        ),
        migrations.AddField(
            model_name='category',
            name='search_terms',
            field=blog.fields.ListField(blank=True, default=None, null=True, token=','),
        ),
        migrations.AddField(
            model_name='customcss',
            name='slug',
            field=models.SlugField(default='css', max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customcss',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='customjs',
            name='slug',
            field=models.SlugField(default='js', max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customjs',
            name='tag',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='display_date',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False, verbose_name='Display Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Updated'),
        ),
        migrations.AddField(
            model_name='post',
            name='previewable',
            field=models.BooleanField(default=False, verbose_name='Preview'),
        ),
        migrations.AddField(
            model_name='post',
            name='publish_date',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2019, 2, 18, 21, 36, 56, 458929), null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='search_terms',
            field=blog.fields.ListField(blank=True, default=None, null=True, token=',', verbose_name='Search Terms'),
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=colorful.fields.RGBColorField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='font_color',
            field=colorful.fields.RGBColorField(default='#000000'),
        ),
        migrations.AddField(
            model_name='tag',
            name='icon_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='blog/tags/icons/'),
        ),
        migrations.AddField(
            model_name='tag',
            name='search_terms',
            field=blog.fields.ListField(blank=True, default=None, null=True, token=',', verbose_name='Search Terms'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='code_style_sheet',
            field=models.CharField(choices=[('code_default', 'Default'), ('code_monokai', 'Dark')], default='code_default', max_length=40, verbose_name='Code Highlight Style'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='latest_feed_most_recent',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Posts in Most Recent'),
        ),
        migrations.AlterField(
            model_name='blogsettings',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customcss',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customjs',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='css_includes',
            field=models.ManyToManyField(blank=True, to='blog.CustomCSS', verbose_name='CSS Includes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='custom_javascript',
            field=models.FileField(blank=True, default=None, null=True, upload_to='blog/posts/scripts/', verbose_name='Custom Javascript'),
        ),
        migrations.AlterField(
            model_name='post',
            name='icon_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, default=None, null=True, upload_to='blog/posts/icons/', verbose_name='Icon Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='javascript_includes',
            field=models.ManyToManyField(blank=True, to='blog.CustomJS', verbose_name='Javascript Includes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted',
            field=models.DateTimeField(blank=True, db_index=True, default=datetime.datetime(2019, 2, 18, 21, 36, 56, 458911), editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.BooleanField(default=False, verbose_name='Publish'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(max_length=120, unique=True, verbose_name='Link Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='blogsettings',
            name='color_theme',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.ColorTheme'),
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.Author'),
        ),
    ]
